package com.team04.back.domain.weather.weather.enums;

public enum Weather {
    SUNNY, CLOUDY, RAINY, SNOWY, WINDY, HUMID, COLD, WARM, WET, DRY, FOGGY,
    HEAVY_SUNNY, HEAVY_CLOUDY, HEAVY_RAINY, HEAVY_SNOWY, HEAVY_WIND, HEAVY_HUMID, HEAVY_COLD, HEAVY_WARM, HEAVY_WET, HEAVY_DRY, HEAVY_FOGGY
}
